### PR TITLE
added ability to plot planned_path from moveit and made rqt launch file

### PR DESCRIPTION
**Pull request by MarqRazz**
First off thanks for making this RQT plugin!!!

I have added the ability to plot planned paths from MoveIt and also made a launch file that pulls up 3 instances of the plot tool inside of RQT. This is useful to plot position, velocity and acceleration for each joint on their own plot. I updated the readme to show how to do this and what it looks like. When I get the chance I am going to make another option in each plot window's selection area that will allow the user to automatically select all published position, velocity or acceleration for that plot.

Please let me know if you would like me to update anything.

### CODE REVIEW

**Comment by 7675t** [comment]
@MarqRazz Can you rebase from maser to make the CI pass?

**Comment by MarqRazz** [comment]
@7675t I can rebase it but wont have time to do it for a little while. Sorry for the delay.

**Comment by MarqRazz** [comment]
Sorry it took me so long to get back to this @7675t.
Just let me know if you would like any other changes.

**Comment by v4hn** [comment]
@7675t ping? This would be really useful to have upstream!

**Pull request merged**
